apiVersion: v1
kind: Service
metadata:
  name: inference-server
  labels:
    app: inference-server
spec:
  type: NodePort
  selector:
    app: inference-server
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30080
    - name: grpc
      port: 8001
      targetPort: 8001
    - name: metrics
      port: 8002
      targetPort: 8002
