// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: inference/kfs/kserve_grpc.proto

package kfs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerLiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerLiveRequest) Reset() {
	*x = ServerLiveRequest{}
	mi := &file_inference_kfs_kserve_grpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerLiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerLiveRequest) ProtoMessage() {}

func (x *ServerLiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_kfs_kserve_grpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerLiveRequest.ProtoReflect.Descriptor instead.
func (*ServerLiveRequest) Descriptor() ([]byte, []int) {
	return file_inference_kfs_kserve_grpc_proto_rawDescGZIP(), []int{0}
}

type ServerLiveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Live          bool                   `protobuf:"varint,1,opt,name=live,proto3" json:"live,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerLiveResponse) Reset() {
	*x = ServerLiveResponse{}
	mi := &file_inference_kfs_kserve_grpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerLiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerLiveResponse) ProtoMessage() {}

func (x *ServerLiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_kfs_kserve_grpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerLiveResponse.ProtoReflect.Descriptor instead.
func (*ServerLiveResponse) Descriptor() ([]byte, []int) {
	return file_inference_kfs_kserve_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *ServerLiveResponse) GetLive() bool {
	if x != nil {
		return x.Live
	}
	return false
}

type ServerReadyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerReadyRequest) Reset() {
	*x = ServerReadyRequest{}
	mi := &file_inference_kfs_kserve_grpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerReadyRequest) ProtoMessage() {}

func (x *ServerReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_kfs_kserve_grpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerReadyRequest.ProtoReflect.Descriptor instead.
func (*ServerReadyRequest) Descriptor() ([]byte, []int) {
	return file_inference_kfs_kserve_grpc_proto_rawDescGZIP(), []int{2}
}

type ServerReadyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerReadyResponse) Reset() {
	*x = ServerReadyResponse{}
	mi := &file_inference_kfs_kserve_grpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerReadyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerReadyResponse) ProtoMessage() {}

func (x *ServerReadyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_kfs_kserve_grpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerReadyResponse.ProtoReflect.Descriptor instead.
func (*ServerReadyResponse) Descriptor() ([]byte, []int) {
	return file_inference_kfs_kserve_grpc_proto_rawDescGZIP(), []int{3}
}

func (x *ServerReadyResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

type ModelReadyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelReadyRequest) Reset() {
	*x = ModelReadyRequest{}
	mi := &file_inference_kfs_kserve_grpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelReadyRequest) ProtoMessage() {}

func (x *ModelReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_kfs_kserve_grpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelReadyRequest.ProtoReflect.Descriptor instead.
func (*ModelReadyRequest) Descriptor() ([]byte, []int) {
	return file_inference_kfs_kserve_grpc_proto_rawDescGZIP(), []int{4}
}

func (x *ModelReadyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelReadyRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ModelReadyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelReadyResponse) Reset() {
	*x = ModelReadyResponse{}
	mi := &file_inference_kfs_kserve_grpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelReadyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelReadyResponse) ProtoMessage() {}

func (x *ModelReadyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_kfs_kserve_grpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelReadyResponse.ProtoReflect.Descriptor instead.
func (*ModelReadyResponse) Descriptor() ([]byte, []int) {
	return file_inference_kfs_kserve_grpc_proto_rawDescGZIP(), []int{5}
}

func (x *ModelReadyResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

type ServerMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMetadataRequest) Reset() {
	*x = ServerMetadataRequest{}
	mi := &file_inference_kfs_kserve_grpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMetadataRequest) ProtoMessage() {}

func (x *ServerMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_kfs_kserve_grpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMetadataRequest.ProtoReflect.Descriptor instead.
func (*ServerMetadataRequest) Descriptor() ([]byte, []int) {
	return file_inference_kfs_kserve_grpc_proto_rawDescGZIP(), []int{6}
}

type ServerMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMetadataResponse) Reset() {
	*x = ServerMetadataResponse{}
	mi := &file_inference_kfs_kserve_grpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMetadataResponse) ProtoMessage() {}

func (x *ServerMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_kfs_kserve_grpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMetadataResponse.ProtoReflect.Descriptor instead.
func (*ServerMetadataResponse) Descriptor() ([]byte, []int) {
	return file_inference_kfs_kserve_grpc_proto_rawDescGZIP(), []int{7}
}

func (x *ServerMetadataResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServerMetadataResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ModelMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelMetadataRequest) Reset() {
	*x = ModelMetadataRequest{}
	mi := &file_inference_kfs_kserve_grpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelMetadataRequest) ProtoMessage() {}

func (x *ModelMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_kfs_kserve_grpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelMetadataRequest.ProtoReflect.Descriptor instead.
func (*ModelMetadataRequest) Descriptor() ([]byte, []int) {
	return file_inference_kfs_kserve_grpc_proto_rawDescGZIP(), []int{8}
}

func (x *ModelMetadataRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelMetadataRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ModelMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Versions      []string               `protobuf:"bytes,2,rep,name=versions,proto3" json:"versions,omitempty"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	Inputs        []*TensorMetadata      `protobuf:"bytes,4,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs       []*TensorMetadata      `protobuf:"bytes,5,rep,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelMetadataResponse) Reset() {
	*x = ModelMetadataResponse{}
	mi := &file_inference_kfs_kserve_grpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelMetadataResponse) ProtoMessage() {}

func (x *ModelMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_kfs_kserve_grpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelMetadataResponse.ProtoReflect.Descriptor instead.
func (*ModelMetadataResponse) Descriptor() ([]byte, []int) {
	return file_inference_kfs_kserve_grpc_proto_rawDescGZIP(), []int{9}
}

func (x *ModelMetadataResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelMetadataResponse) GetVersions() []string {
	if x != nil {
		return x.Versions
	}
	return nil
}

func (x *ModelMetadataResponse) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ModelMetadataResponse) GetInputs() []*TensorMetadata {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *ModelMetadataResponse) GetOutputs() []*TensorMetadata {
	if x != nil {
		return x.Outputs
	}
	return nil
}

type TensorMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Datatype      string                 `protobuf:"bytes,2,opt,name=datatype,proto3" json:"datatype,omitempty"`
	Shape         []int64                `protobuf:"varint,3,rep,packed,name=shape,proto3" json:"shape,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TensorMetadata) Reset() {
	*x = TensorMetadata{}
	mi := &file_inference_kfs_kserve_grpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TensorMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TensorMetadata) ProtoMessage() {}

func (x *TensorMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_inference_kfs_kserve_grpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TensorMetadata.ProtoReflect.Descriptor instead.
func (*TensorMetadata) Descriptor() ([]byte, []int) {
	return file_inference_kfs_kserve_grpc_proto_rawDescGZIP(), []int{10}
}

func (x *TensorMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TensorMetadata) GetDatatype() string {
	if x != nil {
		return x.Datatype
	}
	return ""
}

func (x *TensorMetadata) GetShape() []int64 {
	if x != nil {
		return x.Shape
	}
	return nil
}

type ModelInferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ModelName     string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	ModelVersion  string                 `protobuf:"bytes,3,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	Inputs        []*InferInput          `protobuf:"bytes,4,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs       []*InferOutput         `protobuf:"bytes,5,rep,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelInferRequest) Reset() {
	*x = ModelInferRequest{}
	mi := &file_inference_kfs_kserve_grpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInferRequest) ProtoMessage() {}

func (x *ModelInferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_kfs_kserve_grpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInferRequest.ProtoReflect.Descriptor instead.
func (*ModelInferRequest) Descriptor() ([]byte, []int) {
	return file_inference_kfs_kserve_grpc_proto_rawDescGZIP(), []int{11}
}

func (x *ModelInferRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ModelInferRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *ModelInferRequest) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *ModelInferRequest) GetInputs() []*InferInput {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *ModelInferRequest) GetOutputs() []*InferOutput {
	if x != nil {
		return x.Outputs
	}
	return nil
}

type ModelInferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ModelName     string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	ModelVersion  string                 `protobuf:"bytes,3,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	Outputs       []*InferOutput         `protobuf:"bytes,4,rep,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelInferResponse) Reset() {
	*x = ModelInferResponse{}
	mi := &file_inference_kfs_kserve_grpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInferResponse) ProtoMessage() {}

func (x *ModelInferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_kfs_kserve_grpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInferResponse.ProtoReflect.Descriptor instead.
func (*ModelInferResponse) Descriptor() ([]byte, []int) {
	return file_inference_kfs_kserve_grpc_proto_rawDescGZIP(), []int{12}
}

func (x *ModelInferResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ModelInferResponse) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *ModelInferResponse) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *ModelInferResponse) GetOutputs() []*InferOutput {
	if x != nil {
		return x.Outputs
	}
	return nil
}

type InferInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Shape         []int64                `protobuf:"varint,2,rep,packed,name=shape,proto3" json:"shape,omitempty"`
	Datatype      string                 `protobuf:"bytes,3,opt,name=datatype,proto3" json:"datatype,omitempty"`
	RawData       []byte                 `protobuf:"bytes,4,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferInput) Reset() {
	*x = InferInput{}
	mi := &file_inference_kfs_kserve_grpc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferInput) ProtoMessage() {}

func (x *InferInput) ProtoReflect() protoreflect.Message {
	mi := &file_inference_kfs_kserve_grpc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferInput.ProtoReflect.Descriptor instead.
func (*InferInput) Descriptor() ([]byte, []int) {
	return file_inference_kfs_kserve_grpc_proto_rawDescGZIP(), []int{13}
}

func (x *InferInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InferInput) GetShape() []int64 {
	if x != nil {
		return x.Shape
	}
	return nil
}

func (x *InferInput) GetDatatype() string {
	if x != nil {
		return x.Datatype
	}
	return ""
}

func (x *InferInput) GetRawData() []byte {
	if x != nil {
		return x.RawData
	}
	return nil
}

type InferOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Shape         []int64                `protobuf:"varint,2,rep,packed,name=shape,proto3" json:"shape,omitempty"`
	Datatype      string                 `protobuf:"bytes,3,opt,name=datatype,proto3" json:"datatype,omitempty"`
	RawData       []byte                 `protobuf:"bytes,4,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferOutput) Reset() {
	*x = InferOutput{}
	mi := &file_inference_kfs_kserve_grpc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferOutput) ProtoMessage() {}

func (x *InferOutput) ProtoReflect() protoreflect.Message {
	mi := &file_inference_kfs_kserve_grpc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferOutput.ProtoReflect.Descriptor instead.
func (*InferOutput) Descriptor() ([]byte, []int) {
	return file_inference_kfs_kserve_grpc_proto_rawDescGZIP(), []int{14}
}

func (x *InferOutput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InferOutput) GetShape() []int64 {
	if x != nil {
		return x.Shape
	}
	return nil
}

func (x *InferOutput) GetDatatype() string {
	if x != nil {
		return x.Datatype
	}
	return ""
}

func (x *InferOutput) GetRawData() []byte {
	if x != nil {
		return x.RawData
	}
	return nil
}

var File_inference_kfs_kserve_grpc_proto protoreflect.FileDescriptor

const file_inference_kfs_kserve_grpc_proto_rawDesc = "" +
	"\n" +
	"\x1finference/kfs/kserve_grpc.proto\x12\rinference.kfs\"\x13\n" +
	"\x11ServerLiveRequest\"(\n" +
	"\x12ServerLiveResponse\x12\x12\n" +
	"\x04live\x18\x01 \x01(\bR\x04live\"\x14\n" +
	"\x12ServerReadyRequest\"+\n" +
	"\x13ServerReadyResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\"A\n" +
	"\x11ModelReadyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"*\n" +
	"\x12ModelReadyResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\"\x17\n" +
	"\x15ServerMetadataRequest\"F\n" +
	"\x16ServerMetadataResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"D\n" +
	"\x14ModelMetadataRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\xd3\x01\n" +
	"\x15ModelMetadataResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bversions\x18\x02 \x03(\tR\bversions\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x125\n" +
	"\x06inputs\x18\x04 \x03(\v2\x1d.inference.kfs.TensorMetadataR\x06inputs\x127\n" +
	"\aoutputs\x18\x05 \x03(\v2\x1d.inference.kfs.TensorMetadataR\aoutputs\"V\n" +
	"\x0eTensorMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bdatatype\x18\x02 \x01(\tR\bdatatype\x12\x14\n" +
	"\x05shape\x18\x03 \x03(\x03R\x05shape\"\xd0\x01\n" +
	"\x11ModelInferRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tR\tmodelName\x12#\n" +
	"\rmodel_version\x18\x03 \x01(\tR\fmodelVersion\x121\n" +
	"\x06inputs\x18\x04 \x03(\v2\x19.inference.kfs.InferInputR\x06inputs\x124\n" +
	"\aoutputs\x18\x05 \x03(\v2\x1a.inference.kfs.InferOutputR\aoutputs\"\x9e\x01\n" +
	"\x12ModelInferResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tR\tmodelName\x12#\n" +
	"\rmodel_version\x18\x03 \x01(\tR\fmodelVersion\x124\n" +
	"\aoutputs\x18\x04 \x03(\v2\x1a.inference.kfs.InferOutputR\aoutputs\"m\n" +
	"\n" +
	"InferInput\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05shape\x18\x02 \x03(\x03R\x05shape\x12\x1a\n" +
	"\bdatatype\x18\x03 \x01(\tR\bdatatype\x12\x19\n" +
	"\braw_data\x18\x04 \x01(\fR\arawData\"n\n" +
	"\vInferOutput\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05shape\x18\x02 \x03(\x03R\x05shape\x12\x1a\n" +
	"\bdatatype\x18\x03 \x01(\tR\bdatatype\x12\x19\n" +
	"\braw_data\x18\x04 \x01(\fR\arawData2\xa0\x04\n" +
	"\x14GRPCInferenceService\x12Q\n" +
	"\n" +
	"ServerLive\x12 .inference.kfs.ServerLiveRequest\x1a!.inference.kfs.ServerLiveResponse\x12T\n" +
	"\vServerReady\x12!.inference.kfs.ServerReadyRequest\x1a\".inference.kfs.ServerReadyResponse\x12Q\n" +
	"\n" +
	"ModelReady\x12 .inference.kfs.ModelReadyRequest\x1a!.inference.kfs.ModelReadyResponse\x12]\n" +
	"\x0eServerMetadata\x12$.inference.kfs.ServerMetadataRequest\x1a%.inference.kfs.ServerMetadataResponse\x12Z\n" +
	"\rModelMetadata\x12#.inference.kfs.ModelMetadataRequest\x1a$.inference.kfs.ModelMetadataResponse\x12Q\n" +
	"\n" +
	"ModelInfer\x12 .inference.kfs.ModelInferRequest\x1a!.inference.kfs.ModelInferResponseB\xb7\x01\n" +
	"\x11com.inference.kfsB\x0fKserveGrpcProtoP\x01Z<github.com/mustafacavusoglu/axon/control-plane/inference/kfs\xa2\x02\x03IKX\xaa\x02\rInference.Kfs\xca\x02\rInference\\Kfs\xe2\x02\x19Inference\\Kfs\\GPBMetadata\xea\x02\x0eInference::Kfsb\x06proto3"

var (
	file_inference_kfs_kserve_grpc_proto_rawDescOnce sync.Once
	file_inference_kfs_kserve_grpc_proto_rawDescData []byte
)

func file_inference_kfs_kserve_grpc_proto_rawDescGZIP() []byte {
	file_inference_kfs_kserve_grpc_proto_rawDescOnce.Do(func() {
		file_inference_kfs_kserve_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inference_kfs_kserve_grpc_proto_rawDesc), len(file_inference_kfs_kserve_grpc_proto_rawDesc)))
	})
	return file_inference_kfs_kserve_grpc_proto_rawDescData
}

var file_inference_kfs_kserve_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_inference_kfs_kserve_grpc_proto_goTypes = []any{
	(*ServerLiveRequest)(nil),      // 0: inference.kfs.ServerLiveRequest
	(*ServerLiveResponse)(nil),     // 1: inference.kfs.ServerLiveResponse
	(*ServerReadyRequest)(nil),     // 2: inference.kfs.ServerReadyRequest
	(*ServerReadyResponse)(nil),    // 3: inference.kfs.ServerReadyResponse
	(*ModelReadyRequest)(nil),      // 4: inference.kfs.ModelReadyRequest
	(*ModelReadyResponse)(nil),     // 5: inference.kfs.ModelReadyResponse
	(*ServerMetadataRequest)(nil),  // 6: inference.kfs.ServerMetadataRequest
	(*ServerMetadataResponse)(nil), // 7: inference.kfs.ServerMetadataResponse
	(*ModelMetadataRequest)(nil),   // 8: inference.kfs.ModelMetadataRequest
	(*ModelMetadataResponse)(nil),  // 9: inference.kfs.ModelMetadataResponse
	(*TensorMetadata)(nil),         // 10: inference.kfs.TensorMetadata
	(*ModelInferRequest)(nil),      // 11: inference.kfs.ModelInferRequest
	(*ModelInferResponse)(nil),     // 12: inference.kfs.ModelInferResponse
	(*InferInput)(nil),             // 13: inference.kfs.InferInput
	(*InferOutput)(nil),            // 14: inference.kfs.InferOutput
}
var file_inference_kfs_kserve_grpc_proto_depIdxs = []int32{
	10, // 0: inference.kfs.ModelMetadataResponse.inputs:type_name -> inference.kfs.TensorMetadata
	10, // 1: inference.kfs.ModelMetadataResponse.outputs:type_name -> inference.kfs.TensorMetadata
	13, // 2: inference.kfs.ModelInferRequest.inputs:type_name -> inference.kfs.InferInput
	14, // 3: inference.kfs.ModelInferRequest.outputs:type_name -> inference.kfs.InferOutput
	14, // 4: inference.kfs.ModelInferResponse.outputs:type_name -> inference.kfs.InferOutput
	0,  // 5: inference.kfs.GRPCInferenceService.ServerLive:input_type -> inference.kfs.ServerLiveRequest
	2,  // 6: inference.kfs.GRPCInferenceService.ServerReady:input_type -> inference.kfs.ServerReadyRequest
	4,  // 7: inference.kfs.GRPCInferenceService.ModelReady:input_type -> inference.kfs.ModelReadyRequest
	6,  // 8: inference.kfs.GRPCInferenceService.ServerMetadata:input_type -> inference.kfs.ServerMetadataRequest
	8,  // 9: inference.kfs.GRPCInferenceService.ModelMetadata:input_type -> inference.kfs.ModelMetadataRequest
	11, // 10: inference.kfs.GRPCInferenceService.ModelInfer:input_type -> inference.kfs.ModelInferRequest
	1,  // 11: inference.kfs.GRPCInferenceService.ServerLive:output_type -> inference.kfs.ServerLiveResponse
	3,  // 12: inference.kfs.GRPCInferenceService.ServerReady:output_type -> inference.kfs.ServerReadyResponse
	5,  // 13: inference.kfs.GRPCInferenceService.ModelReady:output_type -> inference.kfs.ModelReadyResponse
	7,  // 14: inference.kfs.GRPCInferenceService.ServerMetadata:output_type -> inference.kfs.ServerMetadataResponse
	9,  // 15: inference.kfs.GRPCInferenceService.ModelMetadata:output_type -> inference.kfs.ModelMetadataResponse
	12, // 16: inference.kfs.GRPCInferenceService.ModelInfer:output_type -> inference.kfs.ModelInferResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_inference_kfs_kserve_grpc_proto_init() }
func file_inference_kfs_kserve_grpc_proto_init() {
	if File_inference_kfs_kserve_grpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inference_kfs_kserve_grpc_proto_rawDesc), len(file_inference_kfs_kserve_grpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inference_kfs_kserve_grpc_proto_goTypes,
		DependencyIndexes: file_inference_kfs_kserve_grpc_proto_depIdxs,
		MessageInfos:      file_inference_kfs_kserve_grpc_proto_msgTypes,
	}.Build()
	File_inference_kfs_kserve_grpc_proto = out.File
	file_inference_kfs_kserve_grpc_proto_goTypes = nil
	file_inference_kfs_kserve_grpc_proto_depIdxs = nil
}
