// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: inference/engine/v1/inference_internal.proto

package enginev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataType int32

const (
	DataType_TYPE_INVALID DataType = 0
	DataType_TYPE_FP32    DataType = 1
	DataType_TYPE_FP64    DataType = 2
	DataType_TYPE_INT32   DataType = 3
	DataType_TYPE_INT64   DataType = 4
	DataType_TYPE_INT8    DataType = 5
	DataType_TYPE_UINT8   DataType = 6
	DataType_TYPE_BOOL    DataType = 7
	DataType_TYPE_STRING  DataType = 8
)

// Enum value maps for DataType.
var (
	DataType_name = map[int32]string{
		0: "TYPE_INVALID",
		1: "TYPE_FP32",
		2: "TYPE_FP64",
		3: "TYPE_INT32",
		4: "TYPE_INT64",
		5: "TYPE_INT8",
		6: "TYPE_UINT8",
		7: "TYPE_BOOL",
		8: "TYPE_STRING",
	}
	DataType_value = map[string]int32{
		"TYPE_INVALID": 0,
		"TYPE_FP32":    1,
		"TYPE_FP64":    2,
		"TYPE_INT32":   3,
		"TYPE_INT64":   4,
		"TYPE_INT8":    5,
		"TYPE_UINT8":   6,
		"TYPE_BOOL":    7,
		"TYPE_STRING":  8,
	}
)

func (x DataType) Enum() *DataType {
	p := new(DataType)
	*p = x
	return p
}

func (x DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_inference_engine_v1_inference_internal_proto_enumTypes[0].Descriptor()
}

func (DataType) Type() protoreflect.EnumType {
	return &file_inference_engine_v1_inference_internal_proto_enumTypes[0]
}

func (x DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataType.Descriptor instead.
func (DataType) EnumDescriptor() ([]byte, []int) {
	return file_inference_engine_v1_inference_internal_proto_rawDescGZIP(), []int{0}
}

type BatchInferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelName     string                 `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Version       uint32                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Inputs        []*InferInput          `protobuf:"bytes,3,rep,name=inputs,proto3" json:"inputs,omitempty"`
	BatchSize     uint32                 `protobuf:"varint,4,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchInferRequest) Reset() {
	*x = BatchInferRequest{}
	mi := &file_inference_engine_v1_inference_internal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchInferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchInferRequest) ProtoMessage() {}

func (x *BatchInferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_engine_v1_inference_internal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchInferRequest.ProtoReflect.Descriptor instead.
func (*BatchInferRequest) Descriptor() ([]byte, []int) {
	return file_inference_engine_v1_inference_internal_proto_rawDescGZIP(), []int{0}
}

func (x *BatchInferRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *BatchInferRequest) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *BatchInferRequest) GetInputs() []*InferInput {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *BatchInferRequest) GetBatchSize() uint32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

type InferInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Shape         []int64                `protobuf:"varint,3,rep,packed,name=shape,proto3" json:"shape,omitempty"`
	Dtype         DataType               `protobuf:"varint,4,opt,name=dtype,proto3,enum=inference.engine.v1.DataType" json:"dtype,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferInput) Reset() {
	*x = InferInput{}
	mi := &file_inference_engine_v1_inference_internal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferInput) ProtoMessage() {}

func (x *InferInput) ProtoReflect() protoreflect.Message {
	mi := &file_inference_engine_v1_inference_internal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferInput.ProtoReflect.Descriptor instead.
func (*InferInput) Descriptor() ([]byte, []int) {
	return file_inference_engine_v1_inference_internal_proto_rawDescGZIP(), []int{1}
}

func (x *InferInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InferInput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *InferInput) GetShape() []int64 {
	if x != nil {
		return x.Shape
	}
	return nil
}

func (x *InferInput) GetDtype() DataType {
	if x != nil {
		return x.Dtype
	}
	return DataType_TYPE_INVALID
}

type BatchInferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outputs       []*InferOutput         `protobuf:"bytes,1,rep,name=outputs,proto3" json:"outputs,omitempty"`
	LatencyMs     float64                `protobuf:"fixed64,2,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchInferResponse) Reset() {
	*x = BatchInferResponse{}
	mi := &file_inference_engine_v1_inference_internal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchInferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchInferResponse) ProtoMessage() {}

func (x *BatchInferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_engine_v1_inference_internal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchInferResponse.ProtoReflect.Descriptor instead.
func (*BatchInferResponse) Descriptor() ([]byte, []int) {
	return file_inference_engine_v1_inference_internal_proto_rawDescGZIP(), []int{2}
}

func (x *BatchInferResponse) GetOutputs() []*InferOutput {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *BatchInferResponse) GetLatencyMs() float64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

type InferOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Shape         []int64                `protobuf:"varint,3,rep,packed,name=shape,proto3" json:"shape,omitempty"`
	Dtype         DataType               `protobuf:"varint,4,opt,name=dtype,proto3,enum=inference.engine.v1.DataType" json:"dtype,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferOutput) Reset() {
	*x = InferOutput{}
	mi := &file_inference_engine_v1_inference_internal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferOutput) ProtoMessage() {}

func (x *InferOutput) ProtoReflect() protoreflect.Message {
	mi := &file_inference_engine_v1_inference_internal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferOutput.ProtoReflect.Descriptor instead.
func (*InferOutput) Descriptor() ([]byte, []int) {
	return file_inference_engine_v1_inference_internal_proto_rawDescGZIP(), []int{3}
}

func (x *InferOutput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InferOutput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *InferOutput) GetShape() []int64 {
	if x != nil {
		return x.Shape
	}
	return nil
}

func (x *InferOutput) GetDtype() DataType {
	if x != nil {
		return x.Dtype
	}
	return DataType_TYPE_INVALID
}

type LoadModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       uint32                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	ModelPath     string                 `protobuf:"bytes,3,opt,name=model_path,json=modelPath,proto3" json:"model_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadModelRequest) Reset() {
	*x = LoadModelRequest{}
	mi := &file_inference_engine_v1_inference_internal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadModelRequest) ProtoMessage() {}

func (x *LoadModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_engine_v1_inference_internal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadModelRequest.ProtoReflect.Descriptor instead.
func (*LoadModelRequest) Descriptor() ([]byte, []int) {
	return file_inference_engine_v1_inference_internal_proto_rawDescGZIP(), []int{4}
}

func (x *LoadModelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LoadModelRequest) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *LoadModelRequest) GetModelPath() string {
	if x != nil {
		return x.ModelPath
	}
	return ""
}

type LoadModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadModelResponse) Reset() {
	*x = LoadModelResponse{}
	mi := &file_inference_engine_v1_inference_internal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadModelResponse) ProtoMessage() {}

func (x *LoadModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_engine_v1_inference_internal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadModelResponse.ProtoReflect.Descriptor instead.
func (*LoadModelResponse) Descriptor() ([]byte, []int) {
	return file_inference_engine_v1_inference_internal_proto_rawDescGZIP(), []int{5}
}

func (x *LoadModelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LoadModelResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UnloadModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       uint32                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnloadModelRequest) Reset() {
	*x = UnloadModelRequest{}
	mi := &file_inference_engine_v1_inference_internal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnloadModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnloadModelRequest) ProtoMessage() {}

func (x *UnloadModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_engine_v1_inference_internal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnloadModelRequest.ProtoReflect.Descriptor instead.
func (*UnloadModelRequest) Descriptor() ([]byte, []int) {
	return file_inference_engine_v1_inference_internal_proto_rawDescGZIP(), []int{6}
}

func (x *UnloadModelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UnloadModelRequest) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type UnloadModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnloadModelResponse) Reset() {
	*x = UnloadModelResponse{}
	mi := &file_inference_engine_v1_inference_internal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnloadModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnloadModelResponse) ProtoMessage() {}

func (x *UnloadModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_engine_v1_inference_internal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnloadModelResponse.ProtoReflect.Descriptor instead.
func (*UnloadModelResponse) Descriptor() ([]byte, []int) {
	return file_inference_engine_v1_inference_internal_proto_rawDescGZIP(), []int{7}
}

func (x *UnloadModelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ModelStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       uint32                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelStatusRequest) Reset() {
	*x = ModelStatusRequest{}
	mi := &file_inference_engine_v1_inference_internal_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelStatusRequest) ProtoMessage() {}

func (x *ModelStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_engine_v1_inference_internal_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelStatusRequest.ProtoReflect.Descriptor instead.
func (*ModelStatusRequest) Descriptor() ([]byte, []int) {
	return file_inference_engine_v1_inference_internal_proto_rawDescGZIP(), []int{8}
}

func (x *ModelStatusRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelStatusRequest) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type ModelStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       uint32                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Platform      string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	MemoryBytes   uint64                 `protobuf:"varint,5,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelStatusResponse) Reset() {
	*x = ModelStatusResponse{}
	mi := &file_inference_engine_v1_inference_internal_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelStatusResponse) ProtoMessage() {}

func (x *ModelStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_engine_v1_inference_internal_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelStatusResponse.ProtoReflect.Descriptor instead.
func (*ModelStatusResponse) Descriptor() ([]byte, []int) {
	return file_inference_engine_v1_inference_internal_proto_rawDescGZIP(), []int{9}
}

func (x *ModelStatusResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelStatusResponse) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ModelStatusResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ModelStatusResponse) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ModelStatusResponse) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_inference_engine_v1_inference_internal_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_engine_v1_inference_internal_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_inference_engine_v1_inference_internal_proto_rawDescGZIP(), []int{10}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	UptimeSec     uint64                 `protobuf:"varint,2,opt,name=uptime_sec,json=uptimeSec,proto3" json:"uptime_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_inference_engine_v1_inference_internal_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_engine_v1_inference_internal_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_inference_engine_v1_inference_internal_proto_rawDescGZIP(), []int{11}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetUptimeSec() uint64 {
	if x != nil {
		return x.UptimeSec
	}
	return 0
}

var File_inference_engine_v1_inference_internal_proto protoreflect.FileDescriptor

const file_inference_engine_v1_inference_internal_proto_rawDesc = "" +
	"\n" +
	",inference/engine/v1/inference_internal.proto\x12\x13inference.engine.v1\"\xa4\x01\n" +
	"\x11BatchInferRequest\x12\x1d\n" +
	"\n" +
	"model_name\x18\x01 \x01(\tR\tmodelName\x12\x18\n" +
	"\aversion\x18\x02 \x01(\rR\aversion\x127\n" +
	"\x06inputs\x18\x03 \x03(\v2\x1f.inference.engine.v1.InferInputR\x06inputs\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x04 \x01(\rR\tbatchSize\"\x7f\n" +
	"\n" +
	"InferInput\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x14\n" +
	"\x05shape\x18\x03 \x03(\x03R\x05shape\x123\n" +
	"\x05dtype\x18\x04 \x01(\x0e2\x1d.inference.engine.v1.DataTypeR\x05dtype\"o\n" +
	"\x12BatchInferResponse\x12:\n" +
	"\aoutputs\x18\x01 \x03(\v2 .inference.engine.v1.InferOutputR\aoutputs\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x02 \x01(\x01R\tlatencyMs\"\x80\x01\n" +
	"\vInferOutput\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x14\n" +
	"\x05shape\x18\x03 \x03(\x03R\x05shape\x123\n" +
	"\x05dtype\x18\x04 \x01(\x0e2\x1d.inference.engine.v1.DataTypeR\x05dtype\"_\n" +
	"\x10LoadModelRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\rR\aversion\x12\x1d\n" +
	"\n" +
	"model_path\x18\x03 \x01(\tR\tmodelPath\"C\n" +
	"\x11LoadModelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"B\n" +
	"\x12UnloadModelRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\rR\aversion\"/\n" +
	"\x13UnloadModelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"B\n" +
	"\x12ModelStatusRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\rR\aversion\"\x98\x01\n" +
	"\x13ModelStatusResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\rR\aversion\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12!\n" +
	"\fmemory_bytes\x18\x05 \x01(\x04R\vmemoryBytes\"\x0f\n" +
	"\rHealthRequest\"I\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x1d\n" +
	"\n" +
	"uptime_sec\x18\x02 \x01(\x04R\tuptimeSec*\x99\x01\n" +
	"\bDataType\x12\x10\n" +
	"\fTYPE_INVALID\x10\x00\x12\r\n" +
	"\tTYPE_FP32\x10\x01\x12\r\n" +
	"\tTYPE_FP64\x10\x02\x12\x0e\n" +
	"\n" +
	"TYPE_INT32\x10\x03\x12\x0e\n" +
	"\n" +
	"TYPE_INT64\x10\x04\x12\r\n" +
	"\tTYPE_INT8\x10\x05\x12\x0e\n" +
	"\n" +
	"TYPE_UINT8\x10\x06\x12\r\n" +
	"\tTYPE_BOOL\x10\a\x12\x0f\n" +
	"\vTYPE_STRING\x10\b2\xe8\x03\n" +
	"\x0fInferenceEngine\x12]\n" +
	"\n" +
	"BatchInfer\x12&.inference.engine.v1.BatchInferRequest\x1a'.inference.engine.v1.BatchInferResponse\x12Z\n" +
	"\tLoadModel\x12%.inference.engine.v1.LoadModelRequest\x1a&.inference.engine.v1.LoadModelResponse\x12`\n" +
	"\vUnloadModel\x12'.inference.engine.v1.UnloadModelRequest\x1a(.inference.engine.v1.UnloadModelResponse\x12`\n" +
	"\vModelStatus\x12'.inference.engine.v1.ModelStatusRequest\x1a(.inference.engine.v1.ModelStatusResponse\x12V\n" +
	"\vHealthcheck\x12\".inference.engine.v1.HealthRequest\x1a#.inference.engine.v1.HealthResponseB\xec\x01\n" +
	"\x17com.inference.engine.v1B\x16InferenceInternalProtoP\x01ZKgithub.com/mustafacavusoglu/axon/control-plane/inference/engine/v1;enginev1\xa2\x02\x03IEX\xaa\x02\x13Inference.Engine.V1\xca\x02\x13Inference\\Engine\\V1\xe2\x02\x1fInference\\Engine\\V1\\GPBMetadata\xea\x02\x15Inference::Engine::V1b\x06proto3"

var (
	file_inference_engine_v1_inference_internal_proto_rawDescOnce sync.Once
	file_inference_engine_v1_inference_internal_proto_rawDescData []byte
)

func file_inference_engine_v1_inference_internal_proto_rawDescGZIP() []byte {
	file_inference_engine_v1_inference_internal_proto_rawDescOnce.Do(func() {
		file_inference_engine_v1_inference_internal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inference_engine_v1_inference_internal_proto_rawDesc), len(file_inference_engine_v1_inference_internal_proto_rawDesc)))
	})
	return file_inference_engine_v1_inference_internal_proto_rawDescData
}

var file_inference_engine_v1_inference_internal_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_inference_engine_v1_inference_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_inference_engine_v1_inference_internal_proto_goTypes = []any{
	(DataType)(0),               // 0: inference.engine.v1.DataType
	(*BatchInferRequest)(nil),   // 1: inference.engine.v1.BatchInferRequest
	(*InferInput)(nil),          // 2: inference.engine.v1.InferInput
	(*BatchInferResponse)(nil),  // 3: inference.engine.v1.BatchInferResponse
	(*InferOutput)(nil),         // 4: inference.engine.v1.InferOutput
	(*LoadModelRequest)(nil),    // 5: inference.engine.v1.LoadModelRequest
	(*LoadModelResponse)(nil),   // 6: inference.engine.v1.LoadModelResponse
	(*UnloadModelRequest)(nil),  // 7: inference.engine.v1.UnloadModelRequest
	(*UnloadModelResponse)(nil), // 8: inference.engine.v1.UnloadModelResponse
	(*ModelStatusRequest)(nil),  // 9: inference.engine.v1.ModelStatusRequest
	(*ModelStatusResponse)(nil), // 10: inference.engine.v1.ModelStatusResponse
	(*HealthRequest)(nil),       // 11: inference.engine.v1.HealthRequest
	(*HealthResponse)(nil),      // 12: inference.engine.v1.HealthResponse
}
var file_inference_engine_v1_inference_internal_proto_depIdxs = []int32{
	2,  // 0: inference.engine.v1.BatchInferRequest.inputs:type_name -> inference.engine.v1.InferInput
	0,  // 1: inference.engine.v1.InferInput.dtype:type_name -> inference.engine.v1.DataType
	4,  // 2: inference.engine.v1.BatchInferResponse.outputs:type_name -> inference.engine.v1.InferOutput
	0,  // 3: inference.engine.v1.InferOutput.dtype:type_name -> inference.engine.v1.DataType
	1,  // 4: inference.engine.v1.InferenceEngine.BatchInfer:input_type -> inference.engine.v1.BatchInferRequest
	5,  // 5: inference.engine.v1.InferenceEngine.LoadModel:input_type -> inference.engine.v1.LoadModelRequest
	7,  // 6: inference.engine.v1.InferenceEngine.UnloadModel:input_type -> inference.engine.v1.UnloadModelRequest
	9,  // 7: inference.engine.v1.InferenceEngine.ModelStatus:input_type -> inference.engine.v1.ModelStatusRequest
	11, // 8: inference.engine.v1.InferenceEngine.Healthcheck:input_type -> inference.engine.v1.HealthRequest
	3,  // 9: inference.engine.v1.InferenceEngine.BatchInfer:output_type -> inference.engine.v1.BatchInferResponse
	6,  // 10: inference.engine.v1.InferenceEngine.LoadModel:output_type -> inference.engine.v1.LoadModelResponse
	8,  // 11: inference.engine.v1.InferenceEngine.UnloadModel:output_type -> inference.engine.v1.UnloadModelResponse
	10, // 12: inference.engine.v1.InferenceEngine.ModelStatus:output_type -> inference.engine.v1.ModelStatusResponse
	12, // 13: inference.engine.v1.InferenceEngine.Healthcheck:output_type -> inference.engine.v1.HealthResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_inference_engine_v1_inference_internal_proto_init() }
func file_inference_engine_v1_inference_internal_proto_init() {
	if File_inference_engine_v1_inference_internal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inference_engine_v1_inference_internal_proto_rawDesc), len(file_inference_engine_v1_inference_internal_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inference_engine_v1_inference_internal_proto_goTypes,
		DependencyIndexes: file_inference_engine_v1_inference_internal_proto_depIdxs,
		EnumInfos:         file_inference_engine_v1_inference_internal_proto_enumTypes,
		MessageInfos:      file_inference_engine_v1_inference_internal_proto_msgTypes,
	}.Build()
	File_inference_engine_v1_inference_internal_proto = out.File
	file_inference_engine_v1_inference_internal_proto_goTypes = nil
	file_inference_engine_v1_inference_internal_proto_depIdxs = nil
}
