// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: inference/engine/v1/inference_internal.proto

package enginev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InferenceEngine_BatchInfer_FullMethodName  = "/inference.engine.v1.InferenceEngine/BatchInfer"
	InferenceEngine_LoadModel_FullMethodName   = "/inference.engine.v1.InferenceEngine/LoadModel"
	InferenceEngine_UnloadModel_FullMethodName = "/inference.engine.v1.InferenceEngine/UnloadModel"
	InferenceEngine_ModelStatus_FullMethodName = "/inference.engine.v1.InferenceEngine/ModelStatus"
	InferenceEngine_Healthcheck_FullMethodName = "/inference.engine.v1.InferenceEngine/Healthcheck"
)

// InferenceEngineClient is the client API for InferenceEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InferenceEngineClient interface {
	BatchInfer(ctx context.Context, in *BatchInferRequest, opts ...grpc.CallOption) (*BatchInferResponse, error)
	LoadModel(ctx context.Context, in *LoadModelRequest, opts ...grpc.CallOption) (*LoadModelResponse, error)
	UnloadModel(ctx context.Context, in *UnloadModelRequest, opts ...grpc.CallOption) (*UnloadModelResponse, error)
	ModelStatus(ctx context.Context, in *ModelStatusRequest, opts ...grpc.CallOption) (*ModelStatusResponse, error)
	Healthcheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type inferenceEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewInferenceEngineClient(cc grpc.ClientConnInterface) InferenceEngineClient {
	return &inferenceEngineClient{cc}
}

func (c *inferenceEngineClient) BatchInfer(ctx context.Context, in *BatchInferRequest, opts ...grpc.CallOption) (*BatchInferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchInferResponse)
	err := c.cc.Invoke(ctx, InferenceEngine_BatchInfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceEngineClient) LoadModel(ctx context.Context, in *LoadModelRequest, opts ...grpc.CallOption) (*LoadModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadModelResponse)
	err := c.cc.Invoke(ctx, InferenceEngine_LoadModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceEngineClient) UnloadModel(ctx context.Context, in *UnloadModelRequest, opts ...grpc.CallOption) (*UnloadModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnloadModelResponse)
	err := c.cc.Invoke(ctx, InferenceEngine_UnloadModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceEngineClient) ModelStatus(ctx context.Context, in *ModelStatusRequest, opts ...grpc.CallOption) (*ModelStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelStatusResponse)
	err := c.cc.Invoke(ctx, InferenceEngine_ModelStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceEngineClient) Healthcheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, InferenceEngine_Healthcheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InferenceEngineServer is the server API for InferenceEngine service.
// All implementations must embed UnimplementedInferenceEngineServer
// for forward compatibility.
type InferenceEngineServer interface {
	BatchInfer(context.Context, *BatchInferRequest) (*BatchInferResponse, error)
	LoadModel(context.Context, *LoadModelRequest) (*LoadModelResponse, error)
	UnloadModel(context.Context, *UnloadModelRequest) (*UnloadModelResponse, error)
	ModelStatus(context.Context, *ModelStatusRequest) (*ModelStatusResponse, error)
	Healthcheck(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedInferenceEngineServer()
}

// UnimplementedInferenceEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInferenceEngineServer struct{}

func (UnimplementedInferenceEngineServer) BatchInfer(context.Context, *BatchInferRequest) (*BatchInferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchInfer not implemented")
}
func (UnimplementedInferenceEngineServer) LoadModel(context.Context, *LoadModelRequest) (*LoadModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadModel not implemented")
}
func (UnimplementedInferenceEngineServer) UnloadModel(context.Context, *UnloadModelRequest) (*UnloadModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnloadModel not implemented")
}
func (UnimplementedInferenceEngineServer) ModelStatus(context.Context, *ModelStatusRequest) (*ModelStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ModelStatus not implemented")
}
func (UnimplementedInferenceEngineServer) Healthcheck(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Healthcheck not implemented")
}
func (UnimplementedInferenceEngineServer) mustEmbedUnimplementedInferenceEngineServer() {}
func (UnimplementedInferenceEngineServer) testEmbeddedByValue()                         {}

// UnsafeInferenceEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InferenceEngineServer will
// result in compilation errors.
type UnsafeInferenceEngineServer interface {
	mustEmbedUnimplementedInferenceEngineServer()
}

func RegisterInferenceEngineServer(s grpc.ServiceRegistrar, srv InferenceEngineServer) {
	// If the following call panics, it indicates UnimplementedInferenceEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InferenceEngine_ServiceDesc, srv)
}

func _InferenceEngine_BatchInfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchInferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceEngineServer).BatchInfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceEngine_BatchInfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceEngineServer).BatchInfer(ctx, req.(*BatchInferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceEngine_LoadModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceEngineServer).LoadModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceEngine_LoadModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceEngineServer).LoadModel(ctx, req.(*LoadModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceEngine_UnloadModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnloadModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceEngineServer).UnloadModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceEngine_UnloadModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceEngineServer).UnloadModel(ctx, req.(*UnloadModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceEngine_ModelStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceEngineServer).ModelStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceEngine_ModelStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceEngineServer).ModelStatus(ctx, req.(*ModelStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceEngine_Healthcheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceEngineServer).Healthcheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceEngine_Healthcheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceEngineServer).Healthcheck(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InferenceEngine_ServiceDesc is the grpc.ServiceDesc for InferenceEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InferenceEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inference.engine.v1.InferenceEngine",
	HandlerType: (*InferenceEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BatchInfer",
			Handler:    _InferenceEngine_BatchInfer_Handler,
		},
		{
			MethodName: "LoadModel",
			Handler:    _InferenceEngine_LoadModel_Handler,
		},
		{
			MethodName: "UnloadModel",
			Handler:    _InferenceEngine_UnloadModel_Handler,
		},
		{
			MethodName: "ModelStatus",
			Handler:    _InferenceEngine_ModelStatus_Handler,
		},
		{
			MethodName: "Healthcheck",
			Handler:    _InferenceEngine_Healthcheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inference/engine/v1/inference_internal.proto",
}
