name: "multi_input_example"
platform: "onnxruntime_onnx"
max_batch_size: 8

input [
  {
    name: "customer_age"
    data_type: TYPE_INT32
    dims: [1]
  },
  {
    name: "account_balance"
    data_type: TYPE_FP32
    dims: [1]
  },
  {
    name: "credit_score"
    data_type: TYPE_INT32
    dims: [1]
  },
  {
    name: "is_active_member"
    data_type: TYPE_INT32
    dims: [1]
  },
  {
    name: "customer_country"
    data_type: TYPE_STRING
    dims: [1]
  }
]

output [
  {
    name: "prediction_probabilities"
    data_type: TYPE_FP32
    dims: [2]
  }
]

instance_group [
  {
    count: 1
    kind: KIND_CPU
  }
]
